name: Update Hit Counter

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (not strictly required, but harmless)
        uses: actions/checkout@v4

      - name: Fetch Neocities API
        run: |
          curl -s "https://neocities.org/api/info?sitename=elswhere" > neocities.json
          # Optional debug:
          jq . neocities.json | sed -e 's/api_key/*****/g'

      - name: Build hits.json
        run: |
          jq '{views: (.info.views // .info.hits), last_updated: .info.last_updated}' neocities.json > hits.json
          cat hits.json

      - name: Update Gist (hits.json)
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}   # PAT with "gist" scope
          GIST_ID:  e000ae8688809341624cece09c0e1690
        run: |
          set -euo pipefail
          # Update the gist file content
          gh api -X PATCH "/gists/$GIST_ID" \
            -f "files[hits.json][content]=$(cat hits.json)"
            
      - name: Verify via API (no CDN cache)
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GIST_ID:  e000ae8688809341624cece09c0e1690
        run: |
          gh api "/gists/$GIST_ID" | jq -r '.files["hits.json"].raw_url'

      - name: Upload hits.json to Neocities
        env:
          NEOCITIES_USERNAME: ${{ secrets.NEOCITIES_USERNAME }}
          NEOCITIES_API_KEY:  ${{ secrets.NEOCITIES_API_KEY }}
        run: |
          # Upload to /data/hits.json on site (Neocities treats the form field name as the remote path)
          curl -sS -u "$NEOCITIES_USERNAME:$NEOCITIES_API_KEY" 
            set -euo pipefail
            -F "data/hits.json=@hits.json;type=application/json" \
            "https://neocities.org/api/upload"

