# .github/workflows/update-hits.yml
name: Update Hit Counter

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch:       # manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Neocities data
        run: |
          curl -s "https://neocities.org/api/info?sitename=elswhere" \
            > neocities.json

      - name: Build hits.json
        run: |
          # extract just views & last_updated
          jq '{views: .info.views}' \
             neocities.json > hits.json

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Debug – show files we just built
        run: |
          echo "----- neocities.json -----"
          cat neocities.json
          echo "----- data/hits.json -----"
          cat ../../data/hits.json

      - name: Update Gist with hits.json
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GIST_ID: ${{ secrets.HITS_GIST_ID }}
        run: |
          # this will PATCH the single file 'hits.json' in your gist
          gh api \
            --method PATCH \
            /gists/$GIST_ID \
            -f files.hits.json.content="$(cat hits.json)"
