name: Update Hit Counter

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:      # manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch Neocities data
      run: |
        curl -s "https://neocities.org/api/info?sitename=elswhere" > neocities.json

    - name: Generate hits.json
      run: |
        jq '{views: .info.views}' neocities.json > data/hits.json

    - name: Commit & push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data/hits.json
        git commit -m "Update hit counter" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/elsieeeyjd/elswhere-neocities.git main
