name: Update Hit Counter
on:
  schedule:
    - cron:  '*/30 * * * *'    # every 30 min
  workflow_dispatch:           # manual run button

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch Neocities data
      run: curl -s "https://neocities.org/api/info?sitename=elswhere" > neocities.json

    - name: Build hits.json
      run: |
        mkdir -p data
        jq '{views: .info.views}' neocities.json > data/hits.json
        echo "----- neocities.json -----"; head -n 20 neocities.json
        echo "----- data/hits.json -----"; cat data/hits.json

    - name: Push back to this repo
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update hit counter"
        file_pattern: "data/hits.json"

    - name: Patch gist
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
        GIST_ID:  e000ae8688809341624cece09c0e1690
      run: |
        # Build a tiny JSON document that looks like:
        # { "files": { "hits.json": { "content": "<the JSON string>" } } }
        jq -Rs --rawfile data data/hits.json '
          {files:{("hits.json"):{content:$data}}}
        ' < /dev/null > gist-payload.json

        cat gist-payload.json  #-- debug, shows what we're sending

        gh api "gists/$GIST_ID" \
          --method PATCH \
          --input gist-payload.json
