name: Update Hit Counter

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:      # manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch Neocities data
      run: |
        curl -s "https://neocities.org/api/info?sitename=elswhere" > neocities.json

    - name: Generate hits.json
      run: |
        jq '{views: .info.views}' neocities.json > data/hits.json
