name: Update Hit Counter

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (not strictly required, but harmless)
        uses: actions/checkout@v4

      - name: Fetch Neocities API
        run: |
          curl -s "https://neocities.org/api/info?sitename=elswhere" > neocities.json
          # Optional debug:
          jq . neocities.json | sed -e 's/api_key/*****/g'

      - name: Build hits.json
        run: |
          jq '{views: .info.views, last_updated: .info.last_updated}' neocities.json > hits.json
          cat hits.json

      - name: Upload hits.json to Neocities
        env:
          NEOCITIES_USERNAME: ${{ secrets.NEOCITIES_USERNAME }}
          NEOCITIES_API_KEY:  ${{ secrets.NEOCITIES_API_KEY }}
        run: |
          # Upload to /data/hits.json on your site (Neocities treats the form field name as the remote path)
          curl -sS -u "$NEOCITIES_USERNAME:$NEOCITIES_API_KEY" \
            -F "data/hits.json=@hits.json" \
            https://neocities.org/api/upload

