name: Update Hit Counter

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:      # manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch Neocities data
      run: |
        curl -s "https://neocities.org/api/info?sitename=elswhere" > neocities.json

    - name: Generate hits.json
      run: |
        jq '{views: .info.views, last_updated: .info.last_updated}' neocities.json > hits.json

    - name: Commit & push if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add hits.json
        git diff --cached --quiet || git commit -m "Update hits.json via GitHub action"
        git push
